---
- name: Include vCenter variables
  include_vars: ../group_vars/vcenter.yml

- name: Extend memory on {{ CompHost }} image
  vmware_guest:
    hostname: vcs01.lab.local
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "{{ vfolder }}"
    datacenter: "{{ vdatacenter }}"
    esxi_hostname: "{{ esxhost }}"
    name: "{{ CompHost }}"
    hardware:
      memory_mb: "{{ vmemory }}"
      hotadd_memory: "{{ vhotaddmemory }}"
    wait_for_ip_address: yes
  delegate_to: localhost
