---
- name: Configure SNMP
  template:
    src: templates/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: 0600
  become: true
  
- name: Restart SNMP interface
  systemd:
    name: snmpd
    state: restarted
  become: true