---
- name: Copy update-checker to server
  copy:
    src: /data/install_files/update_checker/update-checker-install.sh
    dest: /home/admin/update-checker-install.sh
    owner: admin
    group: admin
    mode: 0744

- name: Install update-checker
  command: sh /home/admin/update-checker-install.sh creates=/opt/update-checker/update-checker.sh
  become: true
