---
- name: 'Stop sssd service'
  systemd:
    name: sssd
    state: stopped
  become: true

- name: 'Configure sssd service'
  template:
    src: templates/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  become: true

- name: 'Start sssd service'
  systemd:
    name: sssd
    state: started
  become: true
