- name: Run Summary Script
  shell: |
      echo "-------========Hostname========-------" && echo "$HOSTNAME"
      echo "-------========Disks========-------" && df -hT | grep "dev"
      echo "-------========Data drive mount check========-------" && mount | grep "/data" 
      echo "-------========Network Interfaces========-------" && ip a | grep inet
      echo "-------========Routing========-------" && route -n
      echo "-------========Firewall Ports and Services========-------"  && firewall-cmd --list-all | grep 'ports\|services'
      echo "-------========sysctl.conf settings========-------"  && sysctl -a | grep 'vm.swappiness\|vm.dirty_background_ratio\|vm.dirty_ratio\|net.core.wmem_default\|net.core.rmem_default\|net.core.wmem_max\|net.core.rmem_max\|net.ipv4.tcp_wmem\|net.ipv4.tcp_rmem\|net.ipv4.tcp_window_scaling\|net.ipv4.tcp_max_syn_backlog\|net.core.netdev_max_backlog'
  register: summary_result
  become: true  

- debug: msg={{ summary_result.stdout_lines }}

- name: Simple A record (IPV4 address) lookup for {{ CompHost }}
  command: dig {{ DNSAlias }} +noall +answer
  register: summary_result
  become: true

- debug: msg={{ summary_result.stdout_lines }}

- name: Check network connectivity to gateway1 - {{ vgateway1 }}
  command: ping -c 4 {{ vgateway1 }}
  register: summary_result
  become: true

- debug: msg={{ summary_result.stdout_lines }}

# - name: Check network connectivity to gateway2 - {{ vgateway2 }}
#   command: ping -c 4 {{ vgateway2 }}
#   register: summary_result
#   when:
#     - nicsTotal > 1
#   become: true

# - debug: msg={{ summary_result.stdout_lines }}

- name: Status of SSSD service
  command: systemctl status sssd
  register: summary_result
  become: true
  ignore_errors: yes

- debug: msg={{ summary_result.stdout_lines }}