---
- name: ensure the group WINDOWS_ADMIN_{{ myHostname }} exists
  win_domain_group:
    name: WINDOWS_ADMIN_DC11
    scope: global
    path: OU=Groups,OU=Management,DC=lab,DC=local
    description: WINDOWS ADMINISTRATIVE ACCESS ON DC11
    attributes:
      mail: admins@lab.local
    managed_by: mgarstka
    protect: yes
    state: present
