---
- name: ensure AD group exists
  win_domain_group:
    name: "{{ os }}_ADMIN_{{ CompHost }}"
    scope: global
    path: OU=Groups,OU=Management,DC=lab,DC=local
    description: "{{ os }} ADMINISTRATIVE ACCESS ON {{ CompHost }}"
    managed_by: mgarstka
    protect: yes
    state: present
  delegate_to: dc11
