---
- name: Include vCenter variables
  include_vars: ../group_vars/vcenter.yml

- name: Power Off {{ CompHost }} image
  vmware_guest:
    hostname: vcs01.lab.local
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ CompHost }}"
    state: poweredoff
  delegate_to: localhost
  ignore_errors: yes
