---
- name: Add sysctl.conf entries for REDIS
  lineinfile:
    path: /etc/sysctl.conf
    line: '{{ item }}'
  with_items: "{{ SysctlSettings }}"
  become: true

- name: Applying /etc/sysctl.conf to the kernel
  command: sysctl --system
  become: true