---
- name: Include vCenter variables 
  include_vars: ../group_vars/vcenter.yml 

- name: Create ANSIBLE directory
  win_file:
    path: c:\ANSIBLE
    state: directory
  delegate_to: vcs01

- name: Copy vsphere script file
  win_copy: 
    src: templates/attachvdisk.ps1 
    dest: c:\ANSIBLE\
  delegate_to: vcs01
  when: 
    - vdiskname2attachpersistent == true
    - vdiskname2firsttime == false

- name: Attach virtual disk of {{ CompHost }} from dedicated datastore {{ vdatastore2 }}
  win_shell: c:\ANSIBLE\attachvdisk.ps1 -CompHost {{ CompHost }} -vstore "{{ vdatastore2 }}" -vdisk "{{ vdiskfile2 }}" -vdiskname2 "{{ vdiskname2 }}"
  register: attach_disk_result
  delegate_to: vcs02
  when: 
    - vdiskname2attachpersistent == true
    - vdiskname2firsttime == false

- debug: msg="{{ attach_disk_result }}"
  when: 
    - vdiskname2attachpersistent == true
    - vdiskname2firsttime == false