---
- name: Include vCenter variables
  include_vars: ../group_vars/vcenter.yml

- name: Remove {{ CompHost }} image from vCenter
  vmware_guest:
    hostname: vcs01.lab.local
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ CompHost }}"
    state: absent
  delegate_to: localhost
